---
- name: Ansible provision
  hosts: nodes
  become: yes
  become_user: root
  remote_user: vagrant

  tasks:
    - name: Create directory for ssh-keys
      file:
        state: directory
        mode: 0700
        dest: /root/.ssh/

    - name: Adding rsa-key in /root/.ssh/authorized_keys
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        mode: 0600
      ignore_errors: yes

    - name: Checking DNS
      command: host -t A google.com

    - name: Installing tools
      apt:
        package: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - curl

    - name: Get get-docker script
      get_url:
          url: https://get.docker.com
          dest: /root/get-docker.sh
          mode: '0700'

    - name: Installing docker
      command:
        cmd: /root/get-docker.sh
        creates: /usr/bin/docker

    - name: Add the current user to docker group
      user:
        name: vagrant
        append: yes
        groups: docker
